{
 "title": "BTC/USD Sentiment Analysis",
 "tags": [
  "btc",
  "usd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "BTC/USD Price & Sentiment",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Price" }
   ],
   "targets": [
    {
     "alias": "$tag_exchange",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "exchange" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "currency_price",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=", "value": "BTC/USD" }
     ]
    },
    {
     "alias": "Sentiment",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coin_sentiment",
     "select": [
      [
       { "params": [ "sentiment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "coin", "operator": "=", "value": "BTC" }
     ]
    }
   ]
  },
  {
   "title": "BTC/USD Price",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Price" }
   ],
   "targets": [
    {
     "alias": "$tag_exchange",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "exchange" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "currency_price",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=", "value": "BTC/USD" }
     ]
    }
   ]
  },
  {
   "title": "24hr Bitcoin Sentiment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "sentiment",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "coin_sentiment",
     "select": [
      [
       { "params": [ "sentiment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "coin", "operator": "=", "value": "BTC" }
     ]
    }
   ]
  },
  {
   "title": "Latest 50 Articles",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "article" ], "type": "tag" }
     ],
     "measurement": "articles_history",
     "select": [
      [
       { "params": [ "title" ], "type": "field" }
      ],
      [
       { "params": [ "source" ], "type": "field" }
      ],
      [
       { "params": [ "sentiment" ], "type": "field" }
      ]
     ],
     "slimit": "50"
    }
   ]
  },
  {
   "title": "Top Sources",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "articles_history",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "slimit": "50"
    }
   ]
  },
  {
   "title": "New Articles Added",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "articles added",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "articles_history",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}